### ISSUE TITLE
Implement Bogo Sort

### ISSUE THREAD

**Issue by fundamentals-fontdevelopment** [fundamentals-fontdevelopment/ArrayVisualizer#2]
It is not a distributive sort. Therefore it must be coded all over again.

**Comment by sortingenthusiast** [comment]
What are you talking about? Bogosort IS distributive.

**Comment by fundamentals-fontdevelopment** [comment]
There is nothing distributive about Bogo Sort. It's comparative all the way.

**Comment by fundamentals-fontdevelopment** [comment]
Fixed.
